apiVersion: v1
kind: Service
metadata:
  name: jumphost-svc
spec:
  selector:
    app: jumphost
    tier: jumphost
  type: LoadBalancer
  ports:
  - name: ssh
    protocol: TCP
    port: 22
    targetPort: 22