apiVersion: v1
kind: Service
metadata:
  name: lm-svc
spec:
  selector:
    app: lm
    tier: lm
  type: ClusterIP
  ports:
  - name: ssh
    protocol: TCP
    port: 22
    targetPort: 22
  - name: lm-9961
    protocol: TCP
    port: 9961
    targetPort: 9961
  - name: lm-9962
    protocol: TCP
    port: 9962
    targetPort: 9962
  - name: lm-9963
    protocol: TCP
    port: 9963
    targetPort: 9963